### ISSUE TITLE
Allow typing within pathlist widget

### ISSUE THREAD

**Issue by HCookie** [crahan/ipyfilechooser#77] opened 2024-02-13 09:32 UTC
As #48 detailed, the ability to paste paths or otherwise edit paths within the header path could be useful.

This could be accomplished with a change of widget type of `_pathlist`.

**Comment by crahan** [comment] 2024-02-28 21:36
Thanks for the vote for this feature and the PR. I'll go ahead and close this issue as a duplicate of https://github.com/crahan/ipyfilechooser/issues/48.

**Closed as completed by crahan** 2024-02-28 21:36 UTC
