### ISSUE TITLE
Does not seem to work on Linux

### ISSUE THREAD

**Issue by rolinge** [crahan/ipyfilechooser#15] opened 2020-02-05 19:49 UTC
I tried this on two different linux systems (nVidia Nano under ubuntu and chromium and a regular ubuntu 19 with Firefox).   Neither was able to render the example, the dialog box never appears in the Jupyter notebook.   Any ideas

**Comment by crahan** [comment] 2020-02-05 22:12
I installed a version on Linux Mint using a Python 3.8.0 virtualenv and I did get an error because of an updated version of `ipywidgets` (7.5.1). I downgraded to 7.4.2 and it's working again for me now. Can you verify what `ipywidgets` version you have installed?

**Comment by fslds** [comment] 2020-02-05 22:15
Hi @rolinge!

I have the latest `ipyfilechooser` (0.3.3) and `ipywidgets 7.5.1` installed on Fedora 31, use firefox and chromium and for me it works:
``` python
import ipyfilechooser as fc
print(f"{fc.__name__}.{fc.__version__}")
filewidget = fc.FileChooser('/home/fslds/lab')
filewidget
```
I ran Ubuntu 16.04 before and it worked there too, but did not test yet with ipyfilechooser 0.3.3

- [ ] Are you sure `nodejs` is installed?
     `sudo apt update & sudo apt install nodejs`
- [ ] Are widgets enabled in jupyter notebook or lab?
   - notebook:  `jupyter nbextension enable --py widgetsnbextension`
   - lab: `jupyter labextension install @jupyter-widgets/jupyterlab-manager`
- [ ] Do other widgets render properly?
   -
For more info (for instance if you use *conda*, see: 
https://ipywidgets.readthedocs.io/en/latest/user_install.html

**Comment by crahan** [comment] 2020-02-05 22:39
It looks like the issue resolved itself for me on my Linux Mint install with ipywidgets 7.5.1 after all. I got a GridBox error at first but after upgrading `ipywidgets` to 7.5.1 again and restarting Jupyter Lab the error is now gone.

On macOS I wiped my Jupyter virtualenv and recreated it from scratch, reinstalling the widgets nbextension and labextension as well. Now the issue is gone for me on macOS too. Looks like I was a little to quick to jump to conclusions when things appeared to resolve themselves after downgrading to `ipywidgets` 7.4.2.

**Comment by rolinge** [comment] 2020-02-13 15:39
I will test again at my next opportuntiy on Friday.  It could be that nodeJS was not installed properly.   Thank you for the assistance, very helpful!

**Comment by JamieKidman** [comment] 2020-02-20 15:51
Ive just done a fresh manjaro install and installed nodejs, its working fine, its great tbh. im just trying to find a way to keep adding new files in like an interact function

**Comment by crahan** [comment] 2020-03-05 22:00
@rolinge have you been able to test this again?

**Comment by giswqs** [comment] 2020-04-14 11:57
It works fine on my Manjaro KDE linux. This package is exactly what I am looking for. Thank you very much for developing this! Fantastic work.

**Comment by crahan** [comment] 2020-04-14 11:58
@giswqs thank you for confirming and for the kind words!

**Comment by crahan** [comment] 2020-04-14 12:06
@rolinge I'll close this issue for now. Feel free to open a new issue and reference this one in case you run into continued problems.

**Closed by crahan** 2020-04-14 12:06 UTC
